import path from "node:path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// @ts-expect-error process is a nodejs global
const host = process.env.TAURI_DEV_HOST;

// https://vite.dev/config/
export default defineConfig(async () => ({
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
      "@features-manifest": path.resolve(__dirname, "../preview-features.json"),
      "@tauri-apps/api/core": path.resolve(__dirname, "./src/shared/api/shims/tauri-core-shim.ts"),
      "@tauri-apps/api/event": path.resolve(__dirname, "./src/shared/api/shims/tauri-event-shim.ts"),
      "@tauri-apps/api/window": path.resolve(__dirname, "./src/shared/api/shims/tauri-window-shim.ts"),
      "@tauri-apps/api/webview": path.resolve(__dirname, "./src/shared/api/shims/tauri-webview-shim.ts"),
      "@tauri-apps/api/path": path.resolve(__dirname, "./src/shared/api/shims/tauri-path-shim.ts"),
      "@tauri-apps/api/app": path.resolve(__dirname, "./src/shared/api/shims/tauri-app-shim.ts"),
    },
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: parseInt(process.env.VITE_PORT || "1420", 10),
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
    proxy: {
      // buzz-web: host IPC daemon (agent-daemon-server.js)
      "/api": {
        target: "http://127.0.0.1:3001",
        changeOrigin: true,
      },
    },
  },
}));
